### ISSUE TITLE
Missing code in MidiService

### ISSUE THREAD

**Issue by rs3vans** [snackCake/NerdSoundChallenge#3]
Justin's changes in MidiService (hinted at by changes in MidiController) seem to have been omitted from his pull request. As such, MidiController fails to compile.

**Comment by JustinMullin** [comment]
Sorted in my latest pull request: https://github.com/snackCake/NerdSoundChallenge/pull/5.  Sorry 'bout that.

**Comment by snackCake** [comment]
Fixed
